/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    EditTabs: typeof import('./src/components/EditTabs.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    IconError: typeof import('./src/components/icon/IconError.vue')['default']
    IconFont: typeof import('./src/components/IconFont.vue')['default']
    Iconify: typeof import('./src/components/Iconify.vue')['default']
    IconParkSolidError: typeof import('./src/components/icon/IconParkSolidError.vue')['default']
    JsonEditor: typeof import('./src/components/JsonEditor.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    PageWrapper: typeof import('./src/components/PageWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusIcon: typeof import('./src/components/StatusIcon.vue')['default']
    StatusIconButtonLink: typeof import('./src/components/StatusIconButtonLink.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
