/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    EditTabs: typeof import('./src/components/EditTabs.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Iconify: typeof import('./src/components/Iconify.vue')['default']
    IconParkSolidError: typeof import('./src/components/icon/IconParkSolidError.vue')['default']
    IconParkTree: typeof import('./src/components/icon/IconParkTree.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    MonacoDiffEditor: typeof import('./src/components/MonacoDiffEditor.vue')['default']
    MonacoHeader: typeof import('./src/components/MonacoHeader.vue')['default']
    MonacoJsonEditor: typeof import('./src/components/MonacoJsonEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/SidebarMenu.vue')['default']
    StatusIcon: typeof import('./src/components/StatusIcon.vue')['default']
    StatusIconButtonLink: typeof import('./src/components/StatusIconButtonLink.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VanillaJsonEditor: typeof import('./src/components/VanillaJsonEditor.vue')['default']
  }
}
